version: '3.9'

services:
  mongo:
    image: mongo:5.0.3-focal
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
  
  adminer:
    image: adminer
    restart: always
    ports: 
      - 9091:8080
    links:
      - postgres-db

  postgres-db:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
  
  firefox:
    image: selenium/node-firefox:4.0.0-20211013
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    deploy:
      replicas: 1
    entrypoint: bash -c 'SE_OPTS="--host $$HOSTNAME" /opt/bin/entry_point.sh'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
  
  selenium-hub:
    image: selenium/hub:4.0.0-20211013
    ports:
      - "4444:4444"
    

  payara:
      image: dev_payara
      ports:
        - "4848:4848"
        - "8181:8181"
      links:
        - mongo
        - postgre-db

